config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :places
  resources :categories
  resources :stations
  resources :routes

  # Set a index page

  root 'welcome#index'
  get   'welcome/index'

  #Configuration for generate JSON files from API
  namespace :api, defaults:{ format: :json } do
    namespace :v1 do
      get     "/stations",     to: "api_stations#stationsXroutes"
      get     "/places",       to: "api_places#placesXroutes"
      get     "/categories",   to: "api_categories#categoriesList"
      get     "/routes",   to: "api_routes#routesList"
    end
  end


end

app/models/station.rb
class Station < ApplicationRecord
  has_many :stationroutes
  has_many :routes, :through => :stationroutes

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


  # Get url for JSON structure.
  def image_url
    #current_path = Dir.pwd
    #{root_url} + image.url(:thumb)
    current_path = Dir.pwd
    base_path = current_path + "/public/"
    image_path = image.url(:thumb)
    base_path + image_path
  end



end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
    @stations_routes_list = Stationroute.select("name").joins(:route ).where({station_id: @station.id} )
    @stations_routes_list_compact = @stations_routes_list.map { |c| c.name }
  end

  # GET /stations/new
  def new
    @station = Station.new

    @all_routes = Route.all

    @station_route = @station.stationroutes.build
  end

  # GET /stations/1/edit
  def edit
    @all_routes = Route.all
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    params[:routes][:ids].each do |route|
      if !route.empty?
        @station.stationroutes.build(:route_id => route)
      end
    end

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update

    params[:routes][:ids].each do |route|
      if !route.empty?
        @station.stationroutes.build(:route_id => route)
      end
    end

    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :latitude, :longitude, :image)
    end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.erb
<%= form_with(model: station, local: true ,html: { multipart: true }) do |form| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= form.label :image ,'Imagen'%>
      <%= form.file_field :image, id: :image, :class => 'form-control'%>
    </div>

  <div class="form-group">
    <%= form.label :name , 'Nombre'%>
    <%= form.text_field :name, id: :station_name, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :latitude , 'Latitud' %>
    <%= form.text_field :latitude, id: :station_latitude, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :longitude , 'Longitud' %>
    <%= form.text_field :longitude, id: :station_longitude, :class => 'form-control'%>
  </div>

    <div class="field">
      <%= form.label :Rutas ,'Rutas' %>
      <%= collection_select(:routes, :ids, @all_routes, :id, :name, {}, {:multiple => true}) %>
    </div>

  <div class="actions">
    <%= form.submit station.new_record? ? "Crear Parada" :"Actualizar Parada", :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/stations/edit.html.erb
<div class="container detail-page">
  <h1>Editando Parada</h1>

  <%= render 'form', station: @station %>

  <%= link_to station_path(@station) do %>
      <span class="glyphicon glyphicon-eye-open" data-toggle="tooltip" title="show"></span>
      Ver
  <% end %> |
  <%= link_to stations_path do %>
      <span class="glyphicon glyphicon-arrow-left" data-toggle="tooltip" title="eliminar"></span>
      Paradas
  <% end %>
</div>

app/views/stations/index.html.erb
<div class="container detail-page">
  <p id="notice"><%= notice %></p>

  <h1 class="title-page">Paradas</h1>

  <table class="table">
    <thead>
    <tr>
      <th>Nombre</th>
      <th>Latitud</th>
      <th>Longitud</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @stations.each do |station| %>
        <tr>
          <td><%= station.name %></td>
          <td><%= station.latitude %></td>
          <td><%= station.longitude %></td>
          <td><%= link_to station_path(station) do %>
                <span class="glyphicon glyphicon-eye-open" data-toggle="tooltip" title="show"></span>
                Ver
            <% end %>
          </td>
          <td><%= link_to edit_station_path(station) do %>
                <span class="glyphicon glyphicon-edit" data-toggle="tooltip" title="editar"></span>
                Editar
            <% end %>
          </td>
          <td><%= link_to station_path(station), method: :delete, data: {confirm: 'Esta seguro?'} do %>
                <span class="glyphicon glyphicon-remove-sign" data-toggle="tooltip" title="eliminar"></span>
                Eliminar
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to new_station_path do %>
      <span class="glyphicon glyphicon-plus" data-toggle="tooltip" title="eliminar"></span>
      Nueva Parada
  <% end %>
</div>

app/views/stations/new.html.erb
<div class="container detail-page">
  <h1>Nueva Parada</h1>

  <%= render 'form', station: @station %>

  <%= link_to stations_path do %>
      <span class="glyphicon glyphicon-arrow-left" data-toggle="tooltip" title="eliminar"></span>
      Paradas
  <% end %>
</div>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container stations-detail-page">
  <div class="row">
    <div class="col-md-12">
      <h1 class="title-page">
        <%= @station.name %>
      </h1>

      <p>
        <%= image_tag @station.image.url(:medium) %>
      </p>

      <fieldset>
        <legend> Informacion General</legend>
        <p>
          <strong>Latitud:</strong>
          <%= @station.latitude %>
        </p>

        <p>
          <strong>Longitud:</strong>
          <%= @station.longitude %>
        </p>


        <strong>Rutas:</strong>
        <ol>
          <% @stations_routes_list_compact.each do |element| %>
              <li><%= element %></li>
          <% end %>
        </ol>

        <%= link_to edit_station_path(@station) do %>
            <span class="glyphicon glyphicon-edit" data-toggle="tooltip" title="eliminar"></span>
            Editar
        <% end %>
        |
        <%= link_to stations_path do %>
            <span class="glyphicon glyphicon-arrow-left" data-toggle="tooltip" title="eliminar"></span>
            Paradas
        <% end %>

      </fieldset>
    </div>
  </div>
</div>