config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :places
  resources :categories
  resources :stations
  resources :routes

  # Set a index page

  root 'welcome#index'
  get   'welcome/index'

  #Configuration for generate JSON files from API
  namespace :api, defaults:{ format: :json } do
    namespace :v1 do
      get     "/stations",     to: "api_stations#stationsXroutes"
      get     "/places",       to: "api_places#placesXroutes"
      get     "/categories",   to: "api_categories#categoriesList"
      get     "/routes",   to: "api_routes#routesList"
    end
  end


end

app/models/route.rb
class Route < ApplicationRecord
  validates :name, :presence => true
  validates :observations, :presence => true
  validates :horaLV, :presence => true
  validates :horaS, :presence => true
  validates :horaDF, :presence => true


  has_many :stationroutes
  has_many :stations, :through => :stationroute

  has_many :placeroutes
  has_many :places, :through => :placeroute

end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html {redirect_to @route, notice: 'Route was successfully created.'}
        format.json {render :show, status: :created, location: @route}
      else
        format.html {render :new}
        format.json {render json: @route.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html {redirect_to @route, notice: 'Route was successfully updated.'}
        format.json {render :show, status: :ok, location: @route}
      else
        format.html {render :edit}
        format.json {render json: @route.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html {redirect_to routes_url, notice: 'Route was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_route
    @route = Route.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def route_params
    params.require(:route).permit(:name, :observations, :flotaLV, :horaLV, :interLVP, :interLVN, :flotaS, :horaS, :interSP, :interSN, :flotaDF, :horaDF, :interDFP, :interDFN)
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= form_with(model: route, local: true) do |form| %>
    <% if route.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

          <ul>
            <% route.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= form.label :Nombre %>
      <%= form.text_field :name, id: :route_name, :class => 'form-control' %>
    </div>

    <fieldset>
      <legend>Horarios de Lunes a Viernes</legend>
      <div class="row">
        <div class="col-md-3 col-xs-12">
          <div class="form-group">
            <%= form.label :Flota, 'Flota (Numero de buses)' %>
            <%= form.text_field :flotaLV, id: :flotaLV, :class => 'form-control' %>
          </div>
        </div>

        <div class="col-md-3 col-xs-12">
          <div class="form-group">
            <%= form.label :Horas, 'Horario' %>
            <%= form.text_field :horaLV, id: :horaLV, :class => 'form-control' %>
          </div>
        </div>


        <div class="col-md-3 col-xs-12">
          <div class="form-group">
            <%= form.label :IntervaloPico, 'Intervalo hora pico' %>
            <%= form.text_field :interLVP, id: :interLVP, :class => 'form-control' %>
          </div>
        </div>

        <div class="col-md-3 col-xs-12">
          <div class="form-group">
            <%= form.label :IntervaloNormal, 'Intervalo horario normal' %>
            <%= form.text_field :interLVN, id: :interLVN, :class => 'form-control' %>
          </div>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Horarios Sabado</legend>
      <div class="row">
        <div class="col-md-3 col-xs-12">
          <div class="form-group">
            <%= form.label :flotaS, 'Flota (Numero de buses)' %>
            <%= form.text_field :flotaS, id: :flotaS, :class => 'form-control' %>
          </div>
        </div>
        <div class="col-md-3 col-xs-12">
          <div class="form-group">
            <%= form.label :horaS , 'Horario' %>
            <%= form.text_field :horaS, id: :horaS, :class => 'form-control' %>
          </div>
        </div>

        <div class="col-md-3 col-xs-12">
          <div class="form-group">
            <%= form.label :interSP, 'Intervalo hora pico'  %>
            <%= form.text_field :interSP, id: :interSP, :class => 'form-control' %>
          </div>
        </div>

        <div class="col-md-3 col-xs-12">
          <div class="form-group">
            <%= form.label :interSN , 'Intervalo horario normal' %>
            <%= form.text_field :interSN, id: :interSN, :class => 'form-control' %>
          </div>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Horarios Domingos y Feriados</legend>
      <div class="row">
        <div class="col-md-3 col-xs-12">
          <div class="form-group">
            <%= form.label :flotaDF, 'Flota (Numero de buses)' %>
            <%= form.text_field :flotaDF, id: :flotaDF, :class => 'form-control' %>
          </div>
        </div>

        <div class="col-md-3 col-xs-12">
          <div class="form-group">
            <%= form.label :horaDF , 'Horario'%>
            <%= form.text_field :horaDF, id: :horaDF, :class => 'form-control' %>
          </div>
        </div>

        <div class="col-md-3 col-xs-12">
          <div class="form-group">
            <%= form.label :interDFP ,'Intervalo hora pico'  %>
            <%= form.text_field :interDFP, id: :interDFP, :class => 'form-control' %>
          </div>
        </div>

        <div class="col-md-3 col-xs-12">
          <div class="form-group">
            <%= form.label :interDFN , 'Intervalo horario normal' %>
            <%= form.text_field :interDFN, id: :interDFN, :class => 'form-control' %>
          </div>
        </div>
      </div>
    </fieldset>

    <div class="form-group">
      <%= form.label :Observaciones %>
      <%= form.text_field :observations, id: :route_observations, :class => 'form-control' %>
    </div>


    <div class="actions">
      <%= form.submit route.new_record? ? "Crear Ruta" :"Actualizar Ruta", :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/routes/edit.html.erb
<div class="container detail-page">
  <h1>Editando Ruta</h1>

  <%= render 'form', route: @route %>

  <%= link_to route_path(@route) do %>
      <span class="glyphicon glyphicon-eye-open" data-toggle="tooltip" title="show"></span>
      Ver
  <% end %> |
  <%= link_to routes_path do %>
      <span class="glyphicon glyphicon-arrow-left" data-toggle="tooltip" title="eliminar"></span>
    Rutas
  <% end %>
</div>

app/views/routes/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1 class="title-page">Rutas</h1>

  <table class="table">
    <thead>
    <tr>
      <th>Nombre</th>
      <th>Observaciones</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @routes.each do |route| %>
        <tr>
          <td><%= route.name %></td>
          <td><%= route.observations %></td>
          <td><%= link_to route_path(route) do %>
                <span class="glyphicon glyphicon-eye-open" data-toggle="tooltip" title="eliminar"></span>
                Ver
            <% end %>
          </td>
          <td><%= link_to edit_route_path(route) do %>
                <span class="glyphicon glyphicon-edit" data-toggle="tooltip" title="editar"></span>
                Editar
            <% end %>
          </td>
          <td><%= link_to route_path(route), method: :delete, data: {confirm: 'Esta seguro?'} do %>
                <span class="glyphicon glyphicon-remove-sign" data-toggle="tooltip" title="eliminar"></span>
                Eliminar
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to new_route_path do %>
      <span class="glyphicon glyphicon-plus" data-toggle="tooltip" title="eliminar"></span>
      Nueva Ruta
  <% end %>
</div>

app/views/routes/new.html.erb
<div class="container detail-page">
  <h1>Nueva Ruta</h1>

  <%= render 'form', route: @route %>

  <%= link_to routes_path do %>
      <span class="glyphicon glyphicon-arrow-left" data-toggle="tooltip" title="eliminar"></span>
      Rutas
  <% end %>

</div>

app/views/routes/show.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <div class="row">
    <div class="col-md-12">
      <h1 class="title-page">
        <%= @route.name %>
      </h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <fieldset>
        <legend>Horarios</legend>
        <table class="table">
          <thead>
          <tr>
            <th>Dias</th>
            <th>Horario</th>
            <th>Buses</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td>Lunes - Viernes</td>
            <td><%= @route.horaLV %></td>
            <td><%= @route.flotaLV %></td>
          </tr>
          <tr>
            <td>Sabado</td>
            <td><%= @route.horaS %></td>
            <td><%= @route.flotaS %></td>
          </tr>
          <tr>
            <td>Domingo y Feriados</td>
            <td><%= @route.horaDF %></td>
            <td><%= @route.flotaDF %></td>
          </tr>
          </tbody>
        </table>
      </fieldset>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <fieldset>
        <legend>Intervalos de llegada</legend>
        <table class="table">
          <thead>
          <tr>
            <th>Dias</th>
            <th>Horas Pico</th>
            <th>Normal</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td>Lunes - Viernes</td>
            <td><%= @route.interLVP %></td>
            <td><%= @route.interLVN %></td>
          </tr>
          <tr>
            <td>Sabado</td>
            <td><%= @route.interSP %></td>
            <td><%= @route.interSN %></td>
          </tr>
          <tr>
            <td>Domingo y Feriados</td>
            <td><%= @route.interDFP %></td>
            <td><%= @route.interDFN %></td>
          </tr>
          </tbody>
        </table>
      </fieldset>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <fieldset>
        <legend>Observaciones</legend>
        <p>
          <%= @route.observations %>
        </p>
      </fieldset>
    </div>
  </div>

  <%= link_to edit_route_path(@route) do %>
      <span class="glyphicon glyphicon-edit" data-toggle="tooltip" title="eliminar"></span>
      Editar
  <% end %>
  |
  <%= link_to routes_path do %>
      <span class="glyphicon glyphicon-arrow-left" data-toggle="tooltip" title="eliminar"></span>
      Rutas
  <% end %>
</div>