config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :places
  resources :categories
  resources :stations
  resources :routes

  # Set a index page

  root 'welcome#index'
  get   'welcome/index'

  #Configuration for generate JSON files from API
  namespace :api, defaults:{ format: :json } do
    namespace :v1 do
      get     "/stations",     to: "api_stations#stationsXroutes"
      get     "/places",       to: "api_places#placesXroutes"
      get     "/categories",   to: "api_categories#categoriesList"
      get     "/routes",   to: "api_routes#routesList"
    end
  end


end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :category
  validates :name, :presence => true

  has_many :placeroutes
  has_many :routes, :through => :placeroute

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @places_routes_list = Placeroute.select("name").joins(:route).where({place_id: @place.id})
  end

  # GET /places/new
  def new
    @place = Place.new
    @all_categories = Category.all
    @all_routes = Route.all
    @place_route = @place.placeroutes.build

  end

  # GET /places/1/edit
  def edit
    @all_categories = Category.all
    @all_routes = Route.all
    @place_route = @place.placeroutes.build
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    params[:routes][:ids].each do |route|
      if !route.empty?
        @place.placeroutes.build(:route_id => route)
      end
    end

    respond_to do |format|
      if @place.save
        format.html {redirect_to @place, notice: 'Place was successfully created.'}
        format.json {render :show, status: :created, location: @place}
      else
        format.html {render :new}
        format.json {render json: @place.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update

    params[:routes][:ids].each do |route|
      if !route.empty?
        @place.placeroutes.build(:route_id => route)
      end
    end

    respond_to do |format|
      if @place.update(place_params)
        format.html {redirect_to @place, notice: 'Place was successfully updated.'}
        format.json {render :show, status: :ok, location: @place}
      else
        format.html {render :edit}
        format.json {render json: @place.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html {redirect_to places_url, notice: 'Place was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_place
    @place = Place.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def place_params
    params.require(:place).permit(:name, :category_id ,:placeurl)
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name ,'Nombre'%>
    <%= form.text_field :name, id: :place_name, :class => 'form-control'%>
  </div>

    <div class="form-group">
      <%= form.label :name ,'Url Google Places'%>
      <%= form.text_field :placeurl, id: :place_route, :class => 'form-control'%>
    </div>

    <div class="form-group">
      <%= form.label :Categoria ,'Categoría' %>
      <%= form.collection_select(:category_id, @all_categories, :id, :name, {:prompt=>true}, :class => 'form-control' ) %>
    </div>

    <div class="form-group">
      <%= form.label :Rutas ,'Rutas'%>
      <%= collection_select(:routes, :ids, @all_routes, :id, :name, {}, {:multiple => true}) %>
    </div>



  <div class="actions">
    <%= form.submit place.new_record? ? "Crear Sitio de Interes" :"Actualizar Sitio de Interes" ,:class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/places/edit.html.erb
<div class="container detail-page">
  <h1>Editando Lugar</h1>

  <%= render 'form', place: @place %>

  <%= link_to place_path(@place) do %>
      <span class="glyphicon glyphicon-eye-open" data-toggle="tooltip" title="show"></span>
      Ver
  <% end %> |
  <%= link_to places_path do %>
      <span class="glyphicon glyphicon-arrow-left" data-toggle="tooltip" title="eliminar"></span>
      Lugares
  <% end %>

</div>

app/views/places/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1 class="title-page">Sitios de Interes</h1>

  <table class="table">
    <thead>
    <tr>
      <th>Nombre</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @places.each do |place| %>
        <tr>
          <td><%= place.name %></td>
          <td><%= place.category.name %></td>
          <td><%= link_to place_path(place) do %>
                <span class="glyphicon glyphicon-eye-open" data-toggle="tooltip" title="show"></span>
                Ver
            <% end %>
          </td>
          <td><%= link_to edit_place_path(place) do %>
                <span class="glyphicon glyphicon-edit" data-toggle="tooltip" title="editar"></span>
                Editar
            <% end %>
          </td>
          <td><%= link_to place_path(place), method: :delete, data: {confirm: 'Esta seguro?'} do %>
                <span class="glyphicon glyphicon-remove-sign" data-toggle="tooltip" title="eliminar"></span>
                Eliminar
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to new_place_path do %>
      <span class="glyphicon glyphicon-plus" data-toggle="tooltip" title="eliminar"></span>
      Nuevo Sitio de Interes
  <% end %>
</div>

app/views/places/new.html.erb
<div class="container detail-page">
  <h1>Nuevo Sitio de Interes</h1>

  <%= render 'form', place: @place %>

  <%= link_to places_path do %>
      <span class="glyphicon glyphicon-arrow-left" data-toggle="tooltip" title="eliminar"></span>
      Lugares
  <% end %>

</div>

app/views/places/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="row">
    <div class="col-md-12">
      <h1 class="title-page">
        <%= @place.name %>
      </h1>
      <fieldset>
        <legend>Información General</legend>

        <div class ="iframe-place">
          <iframe
          src="<%= @place.placeurl %>"
          width="600" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>

        <p>
          <strong>Categoria:</strong>
          <%= @place.category.name %>
        </p>

        <p>
          <strong>Rutas:</strong>
        <ol>
          <% @places_routes_list.each do |element| %>
              <li><%= element.name %></li>
          <% end %>
        </ol>
        </p>
      </fieldset>

      <%= link_to edit_place_path(@place) do %>
          <span class="glyphicon glyphicon-edit" data-toggle="tooltip" title="eliminar"></span>
          Editar
      <% end %>
      |
      <%= link_to places_path do %>
          <span class="glyphicon glyphicon-arrow-left" data-toggle="tooltip" title="eliminar"></span>
          Lugares
      <% end %>
    </div>
  </div>

</div>